# Generated by Django 6.0.3 on 2026-04-01 15:03

import colorfield.fields
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', tinymce.models.HTMLField()),
                ('bgcolor', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('bgimage', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('active', models.BooleanField(default=False)),
                ('page', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', tinymce.models.HTMLField()),
                ('bgcolor', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('bgimage', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('active', models.BooleanField(default=False)),
                ('page', models.CharField(blank=True, max_length=50, null=True)),
                ('box', models.IntegerField(choices=[(1, 1)], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', tinymce.models.HTMLField()),
                ('bgcolor', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('bgimage', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('active', models.BooleanField(default=False)),
                ('page', models.CharField(blank=True, max_length=50, null=True)),
                ('is_front', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sides', to='body.card')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
