# Generated by Django 6.0.3 on 2026-05-04 16:01

import core.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebpOrLegacyBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=core.storage.NoSuffixStorage(), upload_to=core.models.get_upload_path, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
