"""
Django settings for portfolio_ws_project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-cm^ubtkjn%cl0y8d=93%vhm(od@my&n+cwb&1%$ycwbi1j97)0')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'
if DEBUG:
    print(f"BASE_DIR set to: {BASE_DIR}")

# CLOUD RUN SERVICE using VPC CONNECTOR - https://cloud.google.com/run/docs/configuring/connecting-vpc#configure-django
hosts = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = hosts.split(',') if hosts else ['127.0.0.1', 'localhost']
if DEBUG:
    print(f"ALLOWED_HOSTS set to: {ALLOWED_HOSTS}")

trusted = os.getenv('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = trusted.split(',') if trusted else []
if DEBUG:
    print(f"CSRF_TRUSTED_ORIGINS set to: {CSRF_TRUSTED_ORIGINS}")

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 3600  # increase to 1 year after cert checks
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_HTTPONLY = True
else:
    SECURE_SSL_REDIRECT = False

# Use X-Forwarded-Host header for request.get_host() when behind a proxy
USE_X_FORWARDED_HOST = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'intro.apps.IntroConfig',
    'core.apps.CoreConfig',
    'body.apps.BodyConfig',
    'link.apps.LinkConfig',
    'tinymce',
    'colorfield',
    'storages',
    'axes',
    'core.templatetags.core_tags',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Lock out an IP after 5 failed attempts for 2 hours
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 2
AXES_RESET_ON_SUCCESS = True 
    
MIDDLEWARE = [
    'portfolio_ws_project.middleware.RedirectWwwMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'portfolio_ws_project.urls'

TINYMCE_DEFAULT_CONFIG = {
    "width": "100%",
    "height": "600px",
    "plugins": "image",
    "toolbar": "undo redo | bold italic | alignleft aligncenter alignright | bullist numlist | image",
    "images_upload_url": "/tinymce-shared/upload-image/",
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'static' / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'intro.context_processors.global_intro',
                'link.context_processors.global_link',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_ws_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

##### ---- ENABLE THIS FOR LOCAL DEVELOPMENT WITH SQLITE -------- #####
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

DB_HOST = os.environ.get("DB_HOST", "db")
'''
##### ---- END ENABLE THIS FOR LOCAL DEVELOPMENT WITH SQLITE ---- #####
##### ---- ENABLE THIS FOR PRODUCTION WITH POSTGRESQL ----------- #####

DB_HOST = os.environ.get("DB_HOST", "db")
DB_NAME = os.environ.get("DB_NAME", "postgres")
DB_USER = os.environ.get("DB_USER", "postgres")
DB_PASS = os.environ.get("DB_PASS", "postgres")

# DO NOT use env.db() here. Use raw os.environ to avoid auto-socket detection.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASS,
        "HOST": DB_HOST,
        "PORT": "5432",
        "OPTIONS": {
            "sslmode": "require", # Enable for non-Debug production environments
            "connect_timeout": 5, # Helps debug timeouts vs socket errors} 
        }
    }
}

if DEBUG:
    print(f"Database configuration: {DATABASES['default']}")

##### ---- END ENABLE THIS FOR PRODUCTION WITH POSTGRESQL ----------- #####

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_DIRS = [BASE_DIR / 'static']

if DB_HOST != 'db':
    from google.cloud import storage

    # Initialize a client
    storage_client = storage.Client()

# Get the bucket
GS_BUCKET_NAME = os.getenv('GS_BUCKET_NAME', None)

if GS_BUCKET_NAME:

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {
                "bucket_name": GS_BUCKET_NAME,
                "location": "media",
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {
                "bucket_name": GS_BUCKET_NAME,
                "location": "static",
            },
        },
    }

    GS_QUERYSTRING_AUTH = False
    #GS_DEFAULT_ACL = None
    MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/media/"
    STATIC_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/static/"
else:
    STATIC_URL = 'static/'
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    STATIC_ROOT = BASE_DIR / 'staticfiles'

if DEBUG:
    print(f"Static and media configuration: STATIC_URL={STATIC_URL}, MEDIA_URL={MEDIA_URL}")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
