# Generated by Django 6.0.3 on 2026-04-01 15:03

import colorfield.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', tinymce.models.HTMLField()),
                ('bgcolor', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('bgimage', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('active', models.BooleanField(default=False)),
                ('page', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('text', models.CharField(blank=True, max_length=15)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', tinymce.models.HTMLField()),
                ('bgcolor', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('bgimage', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('active', models.BooleanField(default=False)),
                ('page', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(choices=[('pre_header', 'Before Header (intro)'), ('post_header', 'After Header (intro)'), ('post_card', 'After Flash Card'), ('pre_footer', 'Before Page Footer')], default='pre_footer', max_length=30)),
                ('justify', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
