# Generated by Django 6.0.3 on 2026-03-24 21:09

import colorfield.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', tinymce.models.HTMLField()),
                ('bgcolor', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('bgimage', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
